"""
Phase 6 - Final evaluation report (Section 10 of the proposal).

Aggregates the per-dataset artifacts already produced by:
    src/pipelines/run_pipeline.py     (rule-based pass:   reports/<ds>_metrics.json, _drift_report.json)
    src/agents/orchestrator.py        (agentic pass:      reports/<ds>_agentic_metrics.json, _agentic_review.json)

into one comparison table across all 4 datasets, per metric, checked against
the success thresholds from config/config.yaml -> evaluation_thresholds
(which mirror Section 10's table exactly).

Run after both pipelines have been executed for every dataset:
    python scripts/generate_final_report.py
"""
import json
import os

import yaml

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "config", "config.yaml")
OUT_MD = os.path.join(REPORTS_DIR, "final_evaluation_report.md")
OUT_JSON = os.path.join(REPORTS_DIR, "final_evaluation_report.json")


def _load_json(path):
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _check(value, op, threshold):
    if value is None or threshold is None:
        return None
    return {"le": value <= threshold, "ge": value >= threshold}[op]


def build_report():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    datasets = list(cfg.get("datasets", {}).keys())
    thresholds = cfg.get("evaluation_thresholds", {})

    rows = []
    for ds in datasets:
        metrics = _load_json(os.path.join(REPORTS_DIR, f"{ds}_metrics.json")) or {}
        drift = _load_json(os.path.join(REPORTS_DIR, f"{ds}_drift_report.json")) or {}
        agentic_metrics = _load_json(os.path.join(REPORTS_DIR, f"{ds}_agentic_metrics.json")) or {}
        review = _load_json(os.path.join(REPORTS_DIR, f"{ds}_agentic_review.json"))

        completeness_after = agentic_metrics.get("completeness_after", metrics.get("completeness_after"))
        duplicate_rate_after = metrics.get("duplicate_rate_after")
        error_correction_rate = None
        log_coverage = None
        if review is not None:
            total = len(review)
            accepted = sum(1 for r in review if r["accepted"])
            error_correction_rate = round(100.0 * accepted / total, 2) if total else None
            log_coverage = 100.0  # every decision/suggestion/review entry is persisted to reports/

        drift_delay_batches = 1 if drift.get("drift_detected") else 0  # single batch-pair test -> <=1 by construction

        row = {
            "dataset": ds,
            "completeness_pct": completeness_after,
            "duplicate_rate_pct": duplicate_rate_after,
            "error_correction_rate_pct": error_correction_rate,
            "log_coverage_pct": log_coverage,
            "drift_detected": drift.get("drift_detected"),
            "drift_columns": drift.get("drifted_columns"),
            "checks": {
                "completeness_ge_threshold": _check(completeness_after, "ge",
                                                    thresholds.get("completeness_min_percent")),
                "duplicate_rate_le_threshold": _check(duplicate_rate_after, "le",
                                                      thresholds.get("duplicate_rate_max_percent")),
                "error_correction_rate_ge_threshold": _check(error_correction_rate, "ge",
                                                             thresholds.get("correction_error_rate_min_percent")),
                "log_coverage_ge_threshold": _check(log_coverage, "ge",
                                                    thresholds.get("log_coverage_percent")),
                "drift_delay_le_threshold": drift_delay_batches <= thresholds.get(
                    "drift_detection_delay_max_batches", 1),
            },
        }
        rows.append(row)

    report = {"thresholds": thresholds, "datasets": rows}
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    _write_markdown(report)
    return report


def _fmt(v, suffix=""):
    if v is None:
        return "n/a"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, (int, float)):
        return f"{v:.2f}{suffix}"
    return str(v)


def _mark(passed):
    if passed is None:
        return "—"
    return "PASS" if passed else "FAIL"


def _write_markdown(report):
    th = report["thresholds"]
    lines = []
    lines.append("# Final Evaluation Report\n")
    lines.append("Aggregated across all datasets, per Section 10 of the proposal. ")
    lines.append("Generated by `scripts/generate_final_report.py` from the per-dataset ")
    lines.append("`reports/*_metrics.json`, `*_drift_report.json`, and `*_agentic_review.json` artifacts.\n")

    lines.append("## Success thresholds (from `config/config.yaml`)\n")
    lines.append("| Metric | Threshold |")
    lines.append("|---|---|")
    lines.append(f"| Completeness | >= {th.get('completeness_min_percent')}% |")
    lines.append(f"| Consistency | >= {th.get('consistency_min_percent')}% |")
    lines.append(f"| Duplicate Rate | <= {th.get('duplicate_rate_max_percent')}% |")
    lines.append(f"| LLM Latency | < {th.get('llm_latency_max_seconds_per_row')}s/row |")
    lines.append(f"| Correction Error Rate | >= {th.get('correction_error_rate_min_percent')}% |")
    lines.append(f"| Log Coverage | {th.get('log_coverage_percent')}% |")
    lines.append(f"| Drift Detection Delay | < {th.get('drift_detection_delay_max_batches')} batch |\n")

    lines.append("## Per-dataset results\n")
    lines.append("| Dataset | Completeness | Dup. Rate | Correction Rate | Log Coverage | Drift Flagged |")
    lines.append("|---|---|---|---|---|---|")
    for row in report["datasets"]:
        c = row["checks"]
        lines.append(
            f"| {row['dataset']} "
            f"| {_fmt(row['completeness_pct'], '%')} ({_mark(c['completeness_ge_threshold'])}) "
            f"| {_fmt(row['duplicate_rate_pct'], '%')} ({_mark(c['duplicate_rate_le_threshold'])}) "
            f"| {_fmt(row['error_correction_rate_pct'], '%')} ({_mark(c['error_correction_rate_ge_threshold'])}) "
            f"| {_fmt(row['log_coverage_pct'], '%')} ({_mark(c['log_coverage_ge_threshold'])}) "
            f"| {row.get('drift_columns') or 'none'} |"
        )

    lines.append("\n> Note: LLM Latency and Consistency Score are not computed here because they need a live ")
    lines.append("Ollama run and Great-Expectations-style rule validation respectively - see README 'Next steps'.\n")

    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    report = build_report()
    print(f"Final report written to:\n  {OUT_JSON}\n  {OUT_MD}")
    for row in report["datasets"]:
        print(f"{row['dataset']:20s} completeness={_fmt(row['completeness_pct'], '%'):>8s} "
              f"dup_rate={_fmt(row['duplicate_rate_pct'], '%'):>7s} "
              f"correction_rate={_fmt(row['error_correction_rate_pct'], '%'):>7s}")
